--------------------------------------------------------------------------------
-- Connect with SYS on XEPDB1
--------------------------------------------------------------------------------
DROP USER sales CASCADE;

CREATE USER sales IDENTIFIED BY sales
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;

grant connect, resource to SALES;
grant CREATE VIEW to sales;
grant create database link to sales;
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DROP USER fdbo CASCADE;

CREATE USER fdbo IDENTIFIED BY fdbo
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON USERS;

grant connect, resource to fdbo;
grant CREATE VIEW to fdbo;
grant create database link to fdbo;

----
grant CREATE ANY DIRECTORY to fdbo;
grant execute on utl_http to fdbo;
grant execute on dbms_lob to fdbo;

--- Permissions for ExcelTable
grant execute on sys.dbms_crypto to fdbo;
select value from v$parameter where name = 'cursor_sharing';

alter session set cursor_sharing = exact;

-- APEX suplimentary permissions
grant CREATE DIMENSION, CREATE JOB, CREATE MATERIALIZED VIEW, CREATE SYNONYM to fdbo;

--------------------------------------------------------------------------------
--- Permissions to invoke REST URLs --------------------------------------------
---
begin
  dbms_network_acl_admin.append_host_ace (
      host       => '*',
      lower_port => NULL,
      upper_port => NULL,
      ace        => xs$ace_type(privilege_list => xs$name_list('http'),
                                principal_name => 'fdbo',
                                principal_type => xs_acl.ptype_db));
  end;
/
COMMIT;

--------------------------------------------------------------------------------
SELECT host,
       lower_port,
       upper_port,
       ace_order,
       TO_CHAR(start_date, 'DD-MON-YYYY') AS start_date,
       TO_CHAR(end_date, 'DD-MON-YYYY') AS end_date,
       grant_type,
       inverted_principal,
       principal,
       principal_type,
       privilege
FROM   dba_host_aces
ORDER BY host, ace_order;
--------------------------------------------------------------------------------

-- Create Tables

CREATE TABLE sales.orders (
  order_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_ts       TIMESTAMP NOT NULL,
  order_status   VARCHAR2(20) NOT NULL,   
  channel        VARCHAR2(20) NOT NULL,   
  cashier_id     NUMBER NULL,             
  total_amount   NUMBER(10,2) NOT NULL
);

CREATE INDEX idx_orders_ts ON sales.orders(order_ts);
CREATE INDEX idx_orders_channel ON sales.orders(channel);

CREATE TABLE sales.order_items (
  order_item_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       NUMBER NOT NULL REFERENCES sales.orders(order_id),
  menu_item_id   NUMBER NOT NULL,                   
  quantity       NUMBER NOT NULL CHECK (quantity > 0),
  unit_price     NUMBER(10,2) NOT NULL,
  line_total     NUMBER(10,2) NOT NULL
);

CREATE INDEX idx_order_items_order ON sales.order_items(order_id);
CREATE INDEX idx_order_items_menu ON sales.order_items(menu_item_id);


CREATE TABLE sales.payments (
  payment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       NUMBER NOT NULL REFERENCES sales.orders(order_id),
  payment_ts     TIMESTAMP NOT NULL,
  method         VARCHAR2(20) NOT NULL,  
  amount         NUMBER(10,2) NOT NULL CHECK (amount >= 0),
  status         VARCHAR2(20) NOT NULL   
);

CREATE INDEX idx_payments_ts ON sales.payments(payment_ts);
CREATE INDEX idx_payments_method ON sales.payments(method);


ALTER TABLE sales.payments
DROP COLUMN status;

ALTER TABLE sales.orders
DROP COLUMN order_status;
