CREATE TABLE sales.orders (
  order_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_ts       TIMESTAMP NOT NULL,
  order_status   VARCHAR2(20) NOT NULL,   
  channel        VARCHAR2(20) NOT NULL,   
  cashier_id     NUMBER NULL,             
  total_amount   NUMBER(10,2) NOT NULL
);

CREATE INDEX idx_orders_ts ON sales.orders(order_ts);
CREATE INDEX idx_orders_channel ON sales.orders(channel);

CREATE TABLE sales.order_items (
  order_item_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       NUMBER NOT NULL REFERENCES sales.orders(order_id),
  menu_item_id   NUMBER NOT NULL,                   
  quantity       NUMBER NOT NULL CHECK (quantity > 0),
  unit_price     NUMBER(10,2) NOT NULL,
  line_total     NUMBER(10,2) NOT NULL
);

CREATE INDEX idx_order_items_order ON sales.order_items(order_id);
CREATE INDEX idx_order_items_menu ON sales.order_items(menu_item_id);


CREATE TABLE sales.payments (
  payment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id       NUMBER NOT NULL REFERENCES sales.orders(order_id),
  payment_ts     TIMESTAMP NOT NULL,
  method         VARCHAR2(20) NOT NULL,  
  amount         NUMBER(10,2) NOT NULL CHECK (amount >= 0),
  status         VARCHAR2(20) NOT NULL   
);

CREATE INDEX idx_payments_ts ON sales.payments(payment_ts);
CREATE INDEX idx_payments_method ON sales.payments(method);


ALTER TABLE sales.payments
DROP COLUMN status;

ALTER TABLE sales.orders
DROP COLUMN order_status;
